### ISSUE TITLE
Image upload with fgci broken

### ISSUE THREAD

**Issue by phillipthelen** [phillipthelen/hardware-fuer-alle#1]
Images (avatar etc.) won't upload, when deployed with fcgi.

**Comment by phillipthelen** [comment]
Fixed.

Image display (in the uploader) doesn't work 100%, because dajaxice can't be loaded (should be fixed when when we switch from /beta/ to /.)

**Comment by optikfluffel** [comment]
maybe moving the beta to beta.domain.com would be a good option?

**Comment by phillipthelen** [comment]
Done. Dajaxice now works. :)
