### ISSUE TITLE
detect duplicate email

### ISSUE THREAD

**Issue by phillipthelen** [phillipthelen/hardware-fuer-alle#10]
If two users have the same email adresses, they are probably the same person. We should offer the possibility to merge two users.

**Comment by mablae** [comment]
Merge? eMail-field should have unique indexes on database level. Never store the same email twice. 

A message: "This email address is already registred" is enough.

**Comment by phillipthelen** [comment]
We Use Djangos built in User, which provides the email field too. This unfortunately doesn't make the field unique. So we have to find a workaround for when a new adress is submitted.
