### ISSUE TITLE
Report abuse function throws MultiValueDictKeyError

### ISSUE THREAD

**Issue by lutoma** [phillipthelen/hardware-fuer-alle#28]
Whilst trying to report an abuse, I got the following error:

MultiValueDictKeyError at /hardware/abuse/
"Key 'object' not found in <QueryDict: {u'csrfmiddlewaretoken': [u'9Yi5B67JlsZ5y5IZR8lUxgmmLasoOXUS'], u'type': [u'main']}>"

**Comment by phillipthelen** [comment]
Can not reproduce the error. (neither in the beta, nor locally.). Sure you can reproduce it?

**Comment by phillipthelen** [comment]
Seems to be fixed?
