### ISSUE TITLE
hfa.settings is missing in repository

### ISSUE THREAD

**Issue by hubx** [phillipthelen/hardware-fuer-alle#32]
_.gitignore_ explicitly excludes it:
/hfa/settings.py

Wanted to a hack a bit at the project, but I was unable to start a development server, due to missing settings.py:
$ python manage.py runserver
**Error: Could not import settings 'hfa.settings' (Is it on sys.path?): No module named settings**

**Comment by phillipthelen** [comment]
Yes, the settings file is missing. As the settings file contains variables that are specific for each setup, it is not included itself. Instead there is an example file that you can use. If you want to setup a working environment copy the /hfa/settings.example.py to /hfa/settings.py and adjust the settings.
