### ISSUE TITLE
changed username not displayed everywhere

### ISSUE THREAD

**Issue by sofakissen** [phillipthelen/hardware-fuer-alle#35]
When the username is changed in the settings, the old username is still displayed in profile URL, list view and smaller on the profile itself.

**Comment by phillipthelen** [comment]
You don't change the username. You change the displayed name (as it also says above the input field.) The Username itself is unique and is set during registration. As it only is needed in the profile url, I chose to make it non editable to prevent bugs.
Alternative "solution": replace the username in the url with the ID and remove it from the profile completely (Doesn't really make sense to have it there anyway.).

**Comment by sofakissen** [comment]
I think the ID in the URL would be fine and less confusing and would also prevent that users can be stuck with a profile name they'd like to remove later (i.e. using Facebook for first login but then later want to remove this connection, but still their Facebook username would be displayed in the profile URL). So I would say: yay for ID in the URL!

Displayed names should be used on hardware profiles and list views (slightly related: https://github.com/vIiRuS/hardware-fuer-alle/issues/34 )

**Comment by phillipthelen** [comment]
Removed the Username everywhere and made the ID the url identifier.
