### ISSUE TITLE
is the post code necessary for user location?

### ISSUE THREAD

**Issue by sofakissen** [phillipthelen/hardware-fuer-alle#37]
When changing the location on my profile the Google map only seems to look for the street and city name. Does the post code matter? If not, it could also be removed (or choosen automaticaly maybe).

**Comment by phillipthelen** [comment]
Postcode isn't always neccessary. As well as the city name. It depends on how unique the postcode/city name is. If it is unique, you don't have to provide the other. But in p.e. Berlin the postcode probably is neccessary, as there are many different postcodes within berlin and sometimes street names aren't unique either.

Also. see Issue https://github.com/vIiRuS/hardware-fuer-alle/issues/31. planning on improving the user experience when entering a location.
