### ISSUE TITLE
Verschenktes als verschenkt markieren

### ISSUE THREAD

**Issue by Lotterleben** [phillipthelen/hardware-fuer-alle#69]
Ich fänd's toll eine History dessen, was bereits verschenkt/verliehen habe, zu sehen. Das könnte Nutzer_innen eventuell helfen die Übersicht zu bewahren und Empfangenden einen Eindruck von der Aktivität des Gegenübers geben.

**Comment by tuxinaut** [comment]
@Lotterleben vielen Dank ich wollte das schon seit Wochen vorschlagen. Ich finde es auch irgendwie komisch verschenkte Sachen zu löschen, die können wie schon gesagt lieber in einer History auftauchen.
